#include <iostream>                                                                                                                                                                                                                                                                       
#include <dlfcn.h>                                                                                                                                                                                                                                                                        
#include <stdint.h>                                                                                                                                                                                                                                                                       
#include <inttypes.h>                                                                                                                                                                                                                                                                     
#include <unordered_map>                                                                                                                                                                                                                                                                  
#include <mutex>                                                                                                                                                                                                                                                                          
#include <string.h>                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                          
// uint32_t djb2_hash(const uint8_t *str) {                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                          
//   uint32_t hash = 5381;                                                                                                                                                                                                                                                                
//   while (uint32_t c = static_cast<uint32_t>(*str++))                                                                                                                                                                                                                                   
//     hash = ((hash << 5)+ hash) +c ;                                                                                                                                                                                                                                                    
//   //  return hash;                                                                                                                                                                                                                                                                     
//   std::cout << "function hash is " << hash;                                                                                                                                                                                                                                            
//   return hash;                                                                                                                                                                                                                                                                         
// }                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                          
// std::unordered_map<void*, uint32_t> hash_cache;                                                                                                                                                                                                                                        
// std::mutex cache_mutex;                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                          
// uint32_t get_func_hash(void *func) {                                                                                                                                                                                                                                                   
//   //#if MEMOIZE_FUNC_HASHES                                                                                                                                                                                                                                                            
//     std::lock_guard<std::mutex> lock(cache_mutex);                                                                                                                                                                                                                                     
//     auto it = hash_cache.find(func);                                                                                                                                                                                                                                                   
//     if (it != hash_cache.end())                                                                                                                                                                                                                                                        
//         return it->second;                                                                                                                                                                                                                                                             
//     //#endif                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                          
//     Dl_info func_info, caller_info;                                                                                                                                                                                                                                                    
//     dladdr(func, &func_info);                                                                                                                                                                                                                                                          
//     auto *func_name = reinterpret_cast<const uint8_t*>(func_info.dli_sname);                                                                                                                                                                                                           
//     uint32_t func_hash = djb2_hash(func_name);                                                                                                                                                                                                                                         
//     //#if MEMOIZE_FUNC_HASHES                                                                                                                                                                                                                                                          
//     hash_cache[func] = func_hash;                                                                                                                                                                                                                                                      
//     //#endif                                                                                                                                                                                                                                                                           
//     return func_hash;                                                                                                                                                                                                                                                                  
// }                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                          
void __cyg_profile_func_enter(void *, void *) __attribute__((no_instrument_function, visibility("default")));                                                                                                                                                                             
                                                                                                                                                                                                                                                                                          
void __cyg_profile_func_enter(void *func, void *call_site) {                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                          
  printf("address %p", func);                                                                                                                                                                                                                                                             
  Dl_info func_info, caller_info;                                                                                                                                                                                                                                                         
  dladdr(func, &func_info);                                                                                                                                                                                                                                                               
  auto *func_name = reinterpret_cast<const uint8_t*>(func_info.dli_sname);                                                                                                                                                                                                                
  const uint8_t *str = func_name ;                                                                                                                                                                                                                                                        
  uint32_t hash = 5381;                                                                                                                                                                                                                                                                   
  while (uint32_t c = static_cast<uint32_t>(*str++))                                                                                                                                                                                                                                        
  hash = ((hash << 5)+ hash) +c ;                                                                                                                                                                                                                                                         
  std::cout << "function hash is " << hash;                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                          
}                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                          
void do_math(int *x) {                                                                                                                                                                                                                                                                    
printf("Inside do_math!\n");                                                                                                                                                                                                                                                              
 *x += 5;       }                                                                                                                                                                                                                                                                         
 int main () {                                                                                                                                                                                                                                                                            
 int result = -1, val = 4;                                                                                                                                                                                                                                                                
 return result;                                                                                                                                                                                                                                                                           
 }  
